{% set name = "Infrared" %}
{% set version = "v1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.inria.fr/amibio/{{ name }}/-/archive/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 727b1b61676b1e49817d81ae90fa29f7b9ac1b1d7bb44f690fc6600427f46f5d

build:
  number: 0
  script:
    - export CMAKE_GENERATOR="Ninja"        # [unix]
    - set "CMAKE_GENERATOR=Ninja"           # [win]
    - set "CMAKE_GENERATOR_PLATFORM="       # [win]
    - set "CMAKE_GENERATOR_TOOLSET="        # [win]
    - "{{ PYTHON }} -m pip install . -vvv"

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - pybind11
    - boost
    - python
    - pip !=22.1.0
  run:
    - python
    - networkx >=2
    - treedecomp

test:
  imports:
    - infrared

about:
  home: "https://gitlab.inria.fr/amibio/Infrared"
  license: "GPL-3.0-only"
  license_family: GPL
  license_file: COPYING
  summary: 'A generic C++/Python hybrid library for efficient (fixed-parameter tractable) Boltzmann sampling'
  description: |
    Infrared provides a fast and flexible C++ engine that evaluates a
    constraint network consisting of variables, multi-ary functions, and
    multi-ary constraints. Functions and constraints are C++ or Python
    objects, where new functions and constraints are easily added in C++
    or in Python
  doc_url: https://www.lix.polytechnique.fr/~will/Software/Infrared/Doc/index.html
  dev_url: https://gitlab.inria.fr/amibio/Infrared

extra:
  recipe-maintainers:
    - anthonyhtyao
    - s-will
