{% set name = "Infrared" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.inria.fr/amibio/{{ name }}/-/archive/v{{ version }}/{{ name }}-v{{ version }}.tar.gz
  sha256: caf7f8887fb6dd0a0bddff9fa1c128579174fe4a99b885b4312bbccdab41d169

build:
  number: 2
  script:
    - export CMAKE_GENERATOR="Ninja"        # [unix]
    - export CMAKE_CXX_STANDARD="17"        # [osx]
    - export CXXFLAGS="-std=c++17"          # [osx]
    - set "CMAKE_GENERATOR=Ninja"           # [win]
    - set "CMAKE_GENERATOR_PLATFORM="       # [win]
    - set "CMAKE_GENERATOR_TOOLSET="        # [win]
    - set "CMAKE_CXX_STANDARD=17"           # [win]
    - set "CXXFLAGS=/std:c++17"             # [win]
    - "{{ PYTHON }} -m pip install . -vvv"

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - pybind11
    - python >=3.8,<=3.12
    - pip !=22.1.0
  run:
    - python >=3.8,<=3.12
    - networkx >=2
    - treedecomp

test:
  imports:
    - infrared

about:
  home: "https://gitlab.inria.fr/amibio/Infrared"
  license: "GPL-3.0-only"
  license_family: GPL
  license_file: COPYING
  summary: 'A declarative framework for tree decomposition powered optimization and Boltzmann sampling'
  description: |
    Infrared allows specifying problems declaratively, which are then
    automatically solved by tree decomposition based efficient algorithms.
    It is therefore well suited for rapid prototyping and development of
    methods that benefit from such techniques. Infrared's
    solvers can either optimize or perform Boltzmann sampling based on defined
    features.  Problems are specified using a modeling
    interface in Python, which also supports the definition of specific
    constraints, functions, and features.  Infrared implements a fast and
    space efficient C++ engine that evaluates the constraint networks.
  doc_url: https://amibio.gitlabpages.inria.fr/infrared/
  dev_url: https://gitlab.inria.fr/amibio/Infrared

extra:
  recipe-maintainers:
    - anthonyhtyao
    - s-will
